# Generated by Django 6.0.1 on 2026-02-17 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_scenario_alter_testcase_scenario'),
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_management_scenarios', to='dashboard.project'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
