# Generated by Django 6.0.1 on 2026-02-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('test_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='test_management.scenario'),
        ),
    ]
