# Generated by Django 6.0.1 on 2026-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_report_status_alter_report_bugs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
