# Generated by Django 6.0.1 on 2026-03-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_bug_assigned_to_alter_bug_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='developer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='fix_file',
            field=models.FileField(blank=True, null=True, upload_to='patches/'),
        ),
    ]
