# Generated by Django 6.0.1 on 2026-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_teamchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
