# Generated by Django 6.0.1 on 2026-03-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_teamchatmessage_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
