# Generated by Django 6.0.1 on 2026-03-16 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_testcase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchatmessage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
            preserve_default=False,
        ),
    ]
