# Generated by Django 6.0.1 on 2026-03-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_teamchatmessage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchatmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
    ]
