# Generated by Django 6.0.1 on 2026-03-16 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_teamchatmessage_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
